---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  dependsOn:
  - name: namespaces
  - name: crds
  interval: 5m
  path: clusters/olympus/manifests/networking/cert-manager
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: olympus
