---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  dependsOn:
  - name: namespaces
  - name: cert-manager
  interval: 5m
  path: clusters/olympus/manifests/networking/certificates
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: olympus
