---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  targetNamespace: network
  dependsOn:
  - name: namespaces
  interval: 5m
  path: deploy/ha
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kubelet-serving-cert-approver-source
