---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 10m0s
  path: clusters/olympus/flux/deploy
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: olympus