---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  targetNamespace: kube-system
  dependsOn:
  - name: namespaces
  - name: kubelet-serving-cert-approver
  interval: 5m
  path: clusters/olympus/manifests/monitoring/metrics-server
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: olympus
