---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 3h
  ref:
    # renovate: datasource=github-releases depName=fluxcd/flux2
    tag: v0.30.2
  url: https://github.com/fluxcd/flux2
  ignore: |
    # exclude all
    /*
    # include manifest dir
    !/manifests