---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  dependsOn:
  - name: external-snapshotter-crds
  interval: 5m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: external-snapshotter-source
  path: deploy/kubernetes/snapshot-controller
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: snapshot-controller
    namespace: kube-system
