---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  targetNamespace: synology-csi
  dependsOn:
  - name: external-snapshotter-crds
  - name: snapshot-controller
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: olympus
  path: clusters/olympus/manifests/storage/synology-csi
  wait: true
  timeout: 1m
  patches:
  - target:
      kind: StatefulSet
      namespace: synology-csi
    patch: |
      - op: add
        path: /spec/template/spec/tolerations
        value:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 25
              preference:
                matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
